// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smartwatch

#ifndef _UI_COMP_FORECASTGROUP_H
#define _UI_COMP_FORECASTGROUP_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT forecastgroup
#define UI_COMP_FORECASTGROUP_FORECASTGROUP 0
#define UI_COMP_FORECASTGROUP_DAY1 1
#define UI_COMP_FORECASTGROUP_DEGREE_GROUP 2
#define UI_COMP_FORECASTGROUP_DEGREE_GROUP_DAYTIME 3
#define UI_COMP_FORECASTGROUP_DEGREE_GROUP_NIGHTTIME 4
#define UI_COMP_FORECASTGROUP_CLOUD_SUN 5
#define _UI_COMP_FORECASTGROUP_NUM 6
lv_obj_t * ui_forecastgroup_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
