// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smartwatch

#include "ui.h"


// COMPONENT todayweathergroup

lv_obj_t * ui_todayweathergroup_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_todayweathergroup;
    cui_todayweathergroup = lv_obj_create(comp_parent);
    lv_obj_set_height(cui_todayweathergroup, 108);
    lv_obj_set_width(cui_todayweathergroup, LV_SIZE_CONTENT);   /// 82
    lv_obj_set_align(cui_todayweathergroup, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_todayweathergroup, LV_FLEX_FLOW_COLUMN_REVERSE);
    lv_obj_set_flex_align(cui_todayweathergroup, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(cui_todayweathergroup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_todayweathergroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_todayweathergroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_todayweathergroup, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_todayweathergroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_degree_6;
    cui_degree_6 = lv_label_create(cui_todayweathergroup);
    lv_obj_set_width(cui_degree_6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_degree_6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_degree_6, 8);
    lv_obj_set_y(cui_degree_6, 0);
    lv_obj_set_align(cui_degree_6, LV_ALIGN_CENTER);
    lv_label_set_text(cui_degree_6, "25°");
    lv_obj_set_style_text_color(cui_degree_6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_degree_6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_degree_6, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_cloud_sun;
    cui_cloud_sun = lv_img_create(cui_todayweathergroup);
    lv_img_set_src(cui_cloud_sun, &ui_img_weather_sun_png);
    lv_obj_set_width(cui_cloud_sun, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_cloud_sun, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_cloud_sun, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_cloud_sun, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_cloud_sun, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_degree_8;
    cui_degree_8 = lv_label_create(cui_todayweathergroup);
    lv_obj_set_width(cui_degree_8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_degree_8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_degree_8, 8);
    lv_obj_set_y(cui_degree_8, 0);
    lv_obj_set_align(cui_degree_8, LV_ALIGN_CENTER);
    lv_label_set_text(cui_degree_8, "Now");
    lv_obj_set_style_text_color(cui_degree_8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_degree_8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_degree_8, &ui_font_Subtitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_TODAYWEATHERGROUP_NUM);
    children[UI_COMP_TODAYWEATHERGROUP_TODAYWEATHERGROUP] = cui_todayweathergroup;
    children[UI_COMP_TODAYWEATHERGROUP_DEGREE_6] = cui_degree_6;
    children[UI_COMP_TODAYWEATHERGROUP_CLOUD_SUN] = cui_cloud_sun;
    children[UI_COMP_TODAYWEATHERGROUP_DEGREE_8] = cui_degree_8;
    lv_obj_add_event_cb(cui_todayweathergroup, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_todayweathergroup, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_todayweathergroup_create_hook(cui_todayweathergroup);
    return cui_todayweathergroup;
}

