// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smartwatch

#ifndef _UI_COMP_WEATHERGROUP1_H
#define _UI_COMP_WEATHERGROUP1_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT weathergroup1
#define UI_COMP_WEATHERGROUP1_WEATHERGROUP1 0
#define UI_COMP_WEATHERGROUP1_DEGREE_1 1
#define UI_COMP_WEATHERGROUP1_CLOUD_FOG_1 2
#define _UI_COMP_WEATHERGROUP1_NUM 3
lv_obj_t * ui_weathergroup1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
