// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smartwatch

#include "ui.h"


// COMPONENT forecastgroup

lv_obj_t * ui_forecastgroup_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_forecastgroup;
    cui_forecastgroup = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_forecastgroup, 259);
    lv_obj_set_height(cui_forecastgroup, 50);
    lv_obj_set_x(cui_forecastgroup, 9);
    lv_obj_set_y(cui_forecastgroup, 79);
    lv_obj_set_align(cui_forecastgroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_forecastgroup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_forecastgroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_forecastgroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_forecastgroup, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_forecastgroup, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_forecastgroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_forecastgroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_day1;
    cui_day1 = lv_label_create(cui_forecastgroup);
    lv_obj_set_width(cui_day1, 53);
    lv_obj_set_height(cui_day1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_day1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_text_color(cui_day1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_day1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_day1, &ui_font_Title, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_degree_group;
    cui_degree_group = lv_obj_create(cui_forecastgroup);
    lv_obj_set_width(cui_degree_group, 100);
    lv_obj_set_height(cui_degree_group, 38);
    lv_obj_set_align(cui_degree_group, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_degree_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_degree_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_degree_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_daytime;
    cui_daytime = lv_label_create(cui_degree_group);
    lv_obj_set_width(cui_daytime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_daytime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_daytime, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_daytime, "25°");
    lv_obj_set_style_text_color(cui_daytime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_daytime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_daytime, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_nighttime;
    cui_nighttime = lv_label_create(cui_degree_group);
    lv_obj_set_width(cui_nighttime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_nighttime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_nighttime, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(cui_nighttime, "25°");
    lv_obj_set_style_text_color(cui_nighttime, lv_color_hex(0x737373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_nighttime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_nighttime, &ui_font_Title, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_cloud_sun;
    cui_cloud_sun = lv_img_create(cui_forecastgroup);
    lv_img_set_src(cui_cloud_sun, &ui_img_weather_sun_png);
    lv_obj_set_width(cui_cloud_sun, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_cloud_sun, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_cloud_sun, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(cui_cloud_sun, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_cloud_sun, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_FORECASTGROUP_NUM);
    children[UI_COMP_FORECASTGROUP_FORECASTGROUP] = cui_forecastgroup;
    children[UI_COMP_FORECASTGROUP_DAY1] = cui_day1;
    children[UI_COMP_FORECASTGROUP_DEGREE_GROUP] = cui_degree_group;
    children[UI_COMP_FORECASTGROUP_DEGREE_GROUP_DAYTIME] = cui_daytime;
    children[UI_COMP_FORECASTGROUP_DEGREE_GROUP_NIGHTTIME] = cui_nighttime;
    children[UI_COMP_FORECASTGROUP_CLOUD_SUN] = cui_cloud_sun;
    lv_obj_add_event_cb(cui_forecastgroup, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_forecastgroup, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_forecastgroup_create_hook(cui_forecastgroup);
    return cui_forecastgroup;
}

