// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smartwatch

#ifndef _UI_COMP_STEPGROUP_H
#define _UI_COMP_STEPGROUP_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT stepgroup
#define UI_COMP_STEPGROUP_STEPGROUP 0
#define UI_COMP_STEPGROUP_STEP 1
#define UI_COMP_STEPGROUP_STEP_LABEL 2
#define _UI_COMP_STEPGROUP_NUM 3
lv_obj_t * ui_stepgroup_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
