// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smartwatch

#ifndef _UI_COMP_TITLEGROUP_H
#define _UI_COMP_TITLEGROUP_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT titlegroup
#define UI_COMP_TITLEGROUP_TITLEGROUP 0
#define UI_COMP_TITLEGROUP_TITLE 1
#define UI_COMP_TITLEGROUP_SUBTITLE 2
#define _UI_COMP_TITLEGROUP_NUM 3
lv_obj_t * ui_titlegroup_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
