// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smartwatch

#ifndef _SMARTWATCH_UI_COMP_HOOK_H
#define _SMARTWATCH_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_batterygroup_create_hook(lv_obj_t * comp);
void ui_comp_buttondown_create_hook(lv_obj_t * comp);
void ui_comp_buttonround_create_hook(lv_obj_t * comp);
void ui_comp_buttontop_create_hook(lv_obj_t * comp);
void ui_comp_dailymissiongroup_create_hook(lv_obj_t * comp);
void ui_comp_dategroup_create_hook(lv_obj_t * comp);
void ui_comp_forecastgroup_create_hook(lv_obj_t * comp);
void ui_comp_pulsegroup_create_hook(lv_obj_t * comp);
void ui_comp_stepgroup_create_hook(lv_obj_t * comp);
void ui_comp_titlegroup_create_hook(lv_obj_t * comp);
void ui_comp_todayweathergroup_create_hook(lv_obj_t * comp);
void ui_comp_weathergroup1_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
