// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smartwatch

#ifndef _UI_COMP_DATEGROUP_H
#define _UI_COMP_DATEGROUP_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT dategroup
#define UI_COMP_DATEGROUP_DATEGROUP 0
#define UI_COMP_DATEGROUP_DAY 1
#define UI_COMP_DATEGROUP_MONTH 2
#define UI_COMP_DATEGROUP_YEAR 3
#define _UI_COMP_DATEGROUP_NUM 4
lv_obj_t * ui_dategroup_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
