// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smartwatch

#ifndef _UI_COMP_BUTTONROUND_H
#define _UI_COMP_BUTTONROUND_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT buttonround
#define UI_COMP_BUTTONROUND_BUTTONROUND 0
#define _UI_COMP_BUTTONROUND_NUM 1
lv_obj_t * ui_buttonround_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
