// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smartwatch

#ifndef _UI_COMP_PULSEGROUP_H
#define _UI_COMP_PULSEGROUP_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT pulsegroup
#define UI_COMP_PULSEGROUP_PULSEGROUP 0
#define UI_COMP_PULSEGROUP_HEART 1
#define UI_COMP_PULSEGROUP_PULSE_NUMBER 2
#define UI_COMP_PULSEGROUP_BPM 3
#define _UI_COMP_PULSEGROUP_NUM 4
lv_obj_t * ui_pulsegroup_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
