// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smartwatch

#include "ui.h"


// COMPONENT pulsegroup

lv_obj_t * ui_pulsegroup_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_pulsegroup;
    cui_pulsegroup = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_pulsegroup, 181);
    lv_obj_set_height(cui_pulsegroup, 50);
    lv_obj_set_x(cui_pulsegroup, 0);
    lv_obj_set_y(cui_pulsegroup, 70);
    lv_obj_set_align(cui_pulsegroup, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_pulsegroup, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_pulsegroup, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(cui_pulsegroup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_pulsegroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_pulsegroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_pulsegroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_pulsegroup, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_heart;
    cui_heart = lv_img_create(cui_pulsegroup);
    lv_img_set_src(cui_heart, &ui_img_heart_png);
    lv_obj_set_width(cui_heart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_heart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_heart, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_heart, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_heart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_pulse_number;
    cui_pulse_number = lv_label_create(cui_pulsegroup);
    lv_obj_set_width(cui_pulse_number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_pulse_number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_pulse_number, LV_ALIGN_CENTER);
    lv_label_set_text(cui_pulse_number, "63");
    lv_obj_set_style_text_color(cui_pulse_number, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_pulse_number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_pulse_number, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_bpm;
    cui_bpm = lv_label_create(cui_pulsegroup);
    lv_obj_set_width(cui_bpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_bpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_bpm, LV_ALIGN_CENTER);
    lv_label_set_text(cui_bpm, "bpm");
    lv_obj_set_style_text_color(cui_bpm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_bpm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_bpm, &ui_font_Title, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PULSEGROUP_NUM);
    children[UI_COMP_PULSEGROUP_PULSEGROUP] = cui_pulsegroup;
    children[UI_COMP_PULSEGROUP_HEART] = cui_heart;
    children[UI_COMP_PULSEGROUP_PULSE_NUMBER] = cui_pulse_number;
    children[UI_COMP_PULSEGROUP_BPM] = cui_bpm;
    lv_obj_add_event_cb(cui_pulsegroup, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_pulsegroup, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_pulsegroup_create_hook(cui_pulsegroup);
    return cui_pulsegroup;
}

