// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smartwatch

#include "ui.h"

void ui_ecg_screen_init(void)
{
    ui_ecg = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ecg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ecg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ecg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_ecg);
    lv_img_set_src(ui_Image1, &ui_img_s8_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 397
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 397
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bg1 = lv_img_create(ui_ecg);
    lv_img_set_src(ui_bg1, &ui_img_bg3_png);
    lv_obj_set_width(ui_bg1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bg1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bg1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_title_group_2 = ui_titlegroup_create(ui_ecg);
    lv_obj_set_x(ui_title_group_2, 0);
    lv_obj_set_y(ui_title_group_2, -303);
    lv_obj_set_align(ui_title_group_2, LV_ALIGN_BOTTOM_MID);

    lv_obj_set_x(ui_comp_get_child(ui_title_group_2, UI_COMP_TITLEGROUP_TITLE), 0);
    lv_obj_set_y(ui_comp_get_child(ui_title_group_2, UI_COMP_TITLEGROUP_TITLE), 0);
    lv_obj_set_align(ui_comp_get_child(ui_title_group_2, UI_COMP_TITLEGROUP_TITLE), LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_comp_get_child(ui_title_group_2, UI_COMP_TITLEGROUP_TITLE), "ECG");
    lv_obj_set_style_text_font(ui_comp_get_child(ui_title_group_2, UI_COMP_TITLEGROUP_TITLE), &ui_font_Subtitle,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(ui_title_group_2, UI_COMP_TITLEGROUP_SUBTITLE), "7 hours ago");

    ui_button_down6 = ui_buttondown_create(ui_ecg);
    lv_obj_set_x(ui_button_down6, 146);
    lv_obj_set_y(ui_button_down6, 102);

    lv_img_set_src(ui_comp_get_child(ui_button_down6, UI_COMP_BUTTONDOWN_BUTTON_DOWN_ICON), &ui_img_house_png);

    ui_button_round1 = ui_buttonround_create(ui_ecg);
    lv_obj_set_x(ui_button_round1, 0);
    lv_obj_set_y(ui_button_round1, -45);

    ui_pulse_group1 = ui_pulsegroup_create(ui_ecg);
    lv_obj_set_x(ui_pulse_group1, 0);
    lv_obj_set_y(ui_pulse_group1, 53);



    ui_health_dots_group1 = lv_obj_create(ui_ecg);
    lv_obj_set_width(ui_health_dots_group1, 102);
    lv_obj_set_height(ui_health_dots_group1, 18);
    lv_obj_set_x(ui_health_dots_group1, 0);
    lv_obj_set_y(ui_health_dots_group1, -15);
    lv_obj_set_align(ui_health_dots_group1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_health_dots_group1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_health_dots_group1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_health_dots_group1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_health_dots_group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_health_dots_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_health_dots_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_health_dots_group1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot9 = lv_obj_create(ui_health_dots_group1);
    lv_obj_set_width(ui_dot9, 6);
    lv_obj_set_height(ui_dot9, 6);
    lv_obj_set_align(ui_dot9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dot9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot9, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot8 = lv_obj_create(ui_health_dots_group1);
    lv_obj_set_width(ui_dot8, 10);
    lv_obj_set_height(ui_dot8, 10);
    lv_obj_set_align(ui_dot8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dot8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot10 = lv_obj_create(ui_health_dots_group1);
    lv_obj_set_width(ui_dot10, 6);
    lv_obj_set_height(ui_dot10, 6);
    lv_obj_set_align(ui_dot10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dot10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot10, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chart_group = lv_obj_create(ui_ecg);
    lv_obj_set_height(ui_chart_group, 117);
    lv_obj_set_width(ui_chart_group, lv_pct(100));
    lv_obj_set_x(ui_chart_group, 0);
    lv_obj_set_y(ui_chart_group, -34);
    lv_obj_set_align(ui_chart_group, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_chart_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chart_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_chart_group, lv_color_hex(0x494949), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chart_group, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_chart_ecg = lv_chart_create(ui_chart_group);
    lv_obj_set_width(ui_chart_ecg, 503);
    lv_obj_set_height(ui_chart_ecg, 100);
    lv_obj_set_align(ui_chart_ecg, LV_ALIGN_LEFT_MID);
    lv_chart_set_type(ui_chart_ecg, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_chart_ecg, 147);
    lv_chart_set_div_line_count(ui_chart_ecg, 10, 40);
    lv_chart_set_axis_tick(ui_chart_ecg, LV_CHART_AXIS_PRIMARY_X, 1, 10, 0, 10, false, 50);
    lv_chart_set_axis_tick(ui_chart_ecg, LV_CHART_AXIS_PRIMARY_Y, 1, 5, 0, 2, false, 50);
    lv_chart_set_axis_tick(ui_chart_ecg, LV_CHART_AXIS_SECONDARY_Y, 0, 5, 1, 2, false, 25);
    lv_chart_series_t * ui_chart_ecg_series_1 = lv_chart_add_series(ui_chart_ecg, lv_color_hex(0xEE1C18),
                                                                    LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_chart_ecg_series_1_array[] = { 20, 20, 21, 24, 25, 24, 22, 25, 18, 90, 10, 24, 25, 28, 38, 39, 28, 24, 23, 25, 27, 27, 25, 22, 20, 20, 20, 21, 24, 25, 24, 22, 25, 18, 90, 10, 24, 25, 28, 38, 39, 28, 24, 23, 25, 27, 27, 25, 22, 20, 20, 20, 21, 24, 25, 24, 22, 25, 18, 90, 10, 24, 25, 28, 38, 39, 28, 24, 23, 25, 27, 27, 25, 22, 20, 20, 21, 24, 25, 24, 22, 25, 18, 90, 10, 24, 25, 28, 38, 39, 28, 24, 23, 25, 27, 27, 25, 22, 20, 20, 21, 24, 25, 24, 22, 25, 18, 90, 10, 24, 25, 28, 38, 39, 28, 24, 23, 25, 27, 27, 25, 22, 20, 20, 21, 24, 25, 24, 22, 25, 18, 90, 10, 24, 25, 28, 38, 39, 28, 24, 23, 25, 27, 27, 25, 22, 20 };
    lv_chart_set_ext_y_array(ui_chart_ecg, ui_chart_ecg_series_1, ui_chart_ecg_series_1_array);
    lv_obj_set_style_bg_color(ui_chart_ecg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chart_ecg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_chart_ecg, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_chart_ecg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_line_width(ui_chart_ecg, 3, LV_PART_ITEMS | LV_STATE_DEFAULT);


    lv_obj_add_event_cb(ui_button_down6, ui_event_button_down6_buttondown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_button_round1, ui_event_button_round1_buttonround, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ecg, ui_event_ecg, LV_EVENT_ALL, NULL);

}
