// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smartwatch

#include "ui.h"

void ui_blood_pressure_screen_init(void)
{
    ui_blood_pressure = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_blood_pressure, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_blood_pressure, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_blood_pressure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bg2 = lv_img_create(ui_blood_pressure);
    lv_img_set_src(ui_bg2, &ui_img_bg3_png);
    lv_obj_set_width(ui_bg2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bg2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bg2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_blood_pressure);
    lv_img_set_src(ui_Image3, &ui_img_s9_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_title_group_3 = ui_titlegroup_create(ui_blood_pressure);
    lv_obj_set_x(ui_title_group_3, 0);
    lv_obj_set_y(ui_title_group_3, -303);
    lv_obj_set_align(ui_title_group_3, LV_ALIGN_BOTTOM_MID);

    lv_obj_set_x(ui_comp_get_child(ui_title_group_3, UI_COMP_TITLEGROUP_TITLE), 0);
    lv_obj_set_y(ui_comp_get_child(ui_title_group_3, UI_COMP_TITLEGROUP_TITLE), 0);
    lv_obj_set_align(ui_comp_get_child(ui_title_group_3, UI_COMP_TITLEGROUP_TITLE), LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_comp_get_child(ui_title_group_3, UI_COMP_TITLEGROUP_TITLE), "Blood Pressure");
    lv_obj_set_style_text_font(ui_comp_get_child(ui_title_group_3, UI_COMP_TITLEGROUP_TITLE), &ui_font_Subtitle,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(ui_title_group_3, UI_COMP_TITLEGROUP_SUBTITLE), "7 hours ago");
    lv_obj_add_flag(ui_comp_get_child(ui_title_group_3, UI_COMP_TITLEGROUP_SUBTITLE), LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_button_down7 = ui_buttondown_create(ui_blood_pressure);
    lv_obj_set_x(ui_button_down7, 146);
    lv_obj_set_y(ui_button_down7, 102);

    lv_img_set_src(ui_comp_get_child(ui_button_down7, UI_COMP_BUTTONDOWN_BUTTON_DOWN_ICON), &ui_img_house_png);

    ui_button_round2 = ui_buttonround_create(ui_blood_pressure);
    lv_obj_set_x(ui_button_round2, 0);
    lv_obj_set_y(ui_button_round2, -45);

    ui_blood_presure_group1 = lv_obj_create(ui_blood_pressure);
    lv_obj_set_width(ui_blood_presure_group1, 186);
    lv_obj_set_height(ui_blood_presure_group1, 140);
    lv_obj_set_x(ui_blood_presure_group1, -83);
    lv_obj_set_y(ui_blood_presure_group1, -2);
    lv_obj_set_align(ui_blood_presure_group1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_blood_presure_group1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_blood_presure_group1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_blood_presure_group1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_blood_presure_group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_blood_presure_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_blood_presure_group1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_blood_presure_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sys_group = lv_obj_create(ui_blood_presure_group1);
    lv_obj_set_width(ui_sys_group, 146);
    lv_obj_set_height(ui_sys_group, 43);
    lv_obj_set_x(ui_sys_group, 36);
    lv_obj_set_y(ui_sys_group, -40);
    lv_obj_set_align(ui_sys_group, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_sys_group, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_sys_group, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sys_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sys_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sys_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_sys_group, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_sys_group, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sys = lv_label_create(ui_sys_group);
    lv_obj_set_width(ui_sys, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sys, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_sys, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sys, "SYS");
    lv_obj_set_style_text_color(ui_sys, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sys, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sys, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mmhg1 = lv_label_create(ui_sys_group);
    lv_obj_set_height(ui_mmhg1, 29);
    lv_obj_set_width(ui_mmhg1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_mmhg1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mmhg1, "mmhg");
    lv_obj_set_style_text_color(ui_mmhg1, lv_color_hex(0x7B7D7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mmhg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mmhg1, &ui_font_Title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_blood_oxygen1 = lv_label_create(ui_blood_presure_group1);
    lv_obj_set_width(ui_blood_oxygen1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_blood_oxygen1, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_align(ui_blood_oxygen1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_blood_oxygen1, "136");
    lv_obj_set_style_text_color(ui_blood_oxygen1, lv_color_hex(0xEE1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_blood_oxygen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_blood_oxygen1, &ui_font_Number_big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pulse_group2 = ui_pulsegroup_create(ui_blood_pressure);
    lv_obj_set_x(ui_pulse_group2, 0);
    lv_obj_set_y(ui_pulse_group2, 67);
    lv_obj_set_align(ui_pulse_group2, LV_ALIGN_TOP_MID);



    ui_blood_presure_group2 = lv_obj_create(ui_blood_pressure);
    lv_obj_set_width(ui_blood_presure_group2, 186);
    lv_obj_set_height(ui_blood_presure_group2, 140);
    lv_obj_set_x(ui_blood_presure_group2, 123);
    lv_obj_set_y(ui_blood_presure_group2, 0);
    lv_obj_set_align(ui_blood_presure_group2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_blood_presure_group2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_blood_presure_group2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_blood_presure_group2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_blood_presure_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_blood_presure_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_blood_presure_group2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_blood_presure_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dia_group = lv_obj_create(ui_blood_presure_group2);
    lv_obj_set_width(ui_dia_group, 146);
    lv_obj_set_height(ui_dia_group, 43);
    lv_obj_set_x(ui_dia_group, 36);
    lv_obj_set_y(ui_dia_group, -40);
    lv_obj_set_align(ui_dia_group, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_dia_group, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_dia_group, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dia_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dia_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dia_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_dia_group, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_dia_group, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dia = lv_label_create(ui_dia_group);
    lv_obj_set_width(ui_dia, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dia, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_dia, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dia, "DIA");
    lv_obj_set_style_text_color(ui_dia, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dia, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dia, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mmhg2 = lv_label_create(ui_dia_group);
    lv_obj_set_height(ui_mmhg2, 29);
    lv_obj_set_width(ui_mmhg2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_mmhg2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mmhg2, "mmhg");
    lv_obj_set_style_text_color(ui_mmhg2, lv_color_hex(0x7B7D7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mmhg2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mmhg2, &ui_font_Title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_blood_oxygen2 = lv_label_create(ui_blood_presure_group2);
    lv_obj_set_width(ui_blood_oxygen2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_blood_oxygen2, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_align(ui_blood_oxygen2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_blood_oxygen2, "85");
    lv_obj_set_style_text_color(ui_blood_oxygen2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_blood_oxygen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_blood_oxygen2, &ui_font_Number_big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_health_dots_group2 = lv_obj_create(ui_blood_pressure);
    lv_obj_set_width(ui_health_dots_group2, 102);
    lv_obj_set_height(ui_health_dots_group2, 18);
    lv_obj_set_x(ui_health_dots_group2, 0);
    lv_obj_set_y(ui_health_dots_group2, -15);
    lv_obj_set_align(ui_health_dots_group2, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_health_dots_group2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_health_dots_group2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_health_dots_group2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_health_dots_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_health_dots_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_health_dots_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_health_dots_group2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot12 = lv_obj_create(ui_health_dots_group2);
    lv_obj_set_width(ui_dot12, 6);
    lv_obj_set_height(ui_dot12, 6);
    lv_obj_set_align(ui_dot12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dot12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot12, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot12, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot13 = lv_obj_create(ui_health_dots_group2);
    lv_obj_set_width(ui_dot13, 6);
    lv_obj_set_height(ui_dot13, 6);
    lv_obj_set_align(ui_dot13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dot13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot13, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot13, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot11 = lv_obj_create(ui_health_dots_group2);
    lv_obj_set_width(ui_dot11, 10);
    lv_obj_set_height(ui_dot11, 10);
    lv_obj_set_align(ui_dot11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dot11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot11, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_button_down7, ui_event_button_down7_buttondown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_button_round2, ui_event_button_round2_buttonround, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_blood_pressure, ui_event_blood_pressure, LV_EVENT_ALL, NULL);

}
