// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smartwatch

#include "ui.h"


// COMPONENT buttonround

lv_obj_t * ui_buttonround_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_buttonround;
    cui_buttonround = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_buttonround, 65);
    lv_obj_set_height(cui_buttonround, 65);
    lv_obj_set_x(cui_buttonround, 0);
    lv_obj_set_y(cui_buttonround, -45);
    lv_obj_set_align(cui_buttonround, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(cui_buttonround, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_buttonround, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_buttonround, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_buttonround, lv_color_hex(0xEE1C18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_buttonround, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(cui_buttonround, &ui_img_measure_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(cui_buttonround, lv_color_hex(0xEE1C18), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(cui_buttonround, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(cui_buttonround, 3, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(cui_buttonround, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(cui_buttonround, lv_color_hex(0xEE1C18), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(cui_buttonround, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(cui_buttonround, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(cui_buttonround, 2, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTONROUND_NUM);
    children[UI_COMP_BUTTONROUND_BUTTONROUND] = cui_buttonround;
    lv_obj_add_event_cb(cui_buttonround, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_buttonround, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_buttonround_create_hook(cui_buttonround);
    return cui_buttonround;
}

