// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smartwatch

#ifndef _UI_COMP_TODAYWEATHERGROUP_H
#define _UI_COMP_TODAYWEATHERGROUP_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT todayweathergroup
#define UI_COMP_TODAYWEATHERGROUP_TODAYWEATHERGROUP 0
#define UI_COMP_TODAYWEATHERGROUP_DEGREE_6 1
#define UI_COMP_TODAYWEATHERGROUP_CLOUD_SUN 2
#define UI_COMP_TODAYWEATHERGROUP_DEGREE_8 3
#define _UI_COMP_TODAYWEATHERGROUP_NUM 4
lv_obj_t * ui_todayweathergroup_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
