// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smartwatch

#include "ui.h"


// COMPONENT titlegroup

lv_obj_t * ui_titlegroup_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_titlegroup;
    cui_titlegroup = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_titlegroup, 200);
    lv_obj_set_height(cui_titlegroup, 50);
    lv_obj_set_x(cui_titlegroup, 13);
    lv_obj_set_y(cui_titlegroup, -83);
    lv_obj_set_align(cui_titlegroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_titlegroup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_titlegroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_titlegroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_title;
    cui_title = lv_label_create(cui_titlegroup);
    lv_obj_set_width(cui_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_title, LV_ALIGN_TOP_MID);
    lv_label_set_text(cui_title, "title");
    lv_obj_set_style_text_color(cui_title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_title, &ui_font_Title, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_subtitle;
    cui_subtitle = lv_label_create(cui_titlegroup);
    lv_obj_set_width(cui_subtitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_subtitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_subtitle, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(cui_subtitle, "subtitle");
    lv_obj_set_style_text_color(cui_subtitle, lv_color_hex(0x6D6D6D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_subtitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_subtitle, &ui_font_Title, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_TITLEGROUP_NUM);
    children[UI_COMP_TITLEGROUP_TITLEGROUP] = cui_titlegroup;
    children[UI_COMP_TITLEGROUP_TITLE] = cui_title;
    children[UI_COMP_TITLEGROUP_SUBTITLE] = cui_subtitle;
    lv_obj_add_event_cb(cui_titlegroup, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_titlegroup, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_titlegroup_create_hook(cui_titlegroup);
    return cui_titlegroup;
}

