// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smartwatch

#ifndef _UI_COMP_BUTTONDOWN_H
#define _UI_COMP_BUTTONDOWN_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT buttondown
#define UI_COMP_BUTTONDOWN_BUTTONDOWN 0
#define UI_COMP_BUTTONDOWN_BUTTON_DOWN_ICON 1
#define UI_COMP_BUTTONDOWN_LINE 2
#define _UI_COMP_BUTTONDOWN_NUM 3
lv_obj_t * ui_buttondown_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
